version: '3.3'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "${DATABASE_NAME}"
#      MONGO_INITDB_ROOT_USERNAME: "${DATABASE_USER}"
#      MONGO_INITDB_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - mongodb_data_container:/data/db
    ports:
      # <Port exposed> : < Mongodb Port running inside container>
      - '27017:27017'
    expose:
      # Opens port 27017 on the container
      - '27017'
  wenance_challange_app:
    container_name: wenance_challange_app
    restart: always
    build: .
    image: wenance_challange_app
    working_dir: /app
    volumes:
      #- ./target:/app/target
      - ./wait-for-it.sh:/app/wait-for-it.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    expose:
      - "8080"
    # debug enabled
    command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh mongo:27017 && /usr/local/openjdk-11/bin/java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005 -jar /app/target/challange-0.0.1-SNAPSHOT.jar"
    # debug disabled
    # command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh mongo:27017 && /usr/local/openjdk-11/bin/java -jar /app/target/challange-0.0.1-SNAPSHOT.jar"
    depends_on:
      - mongo
volumes:
  mongodb_data_container: